window.products=[
    {
        id:1,
        title:'Essential cotton-blend',
        img:'./image/product/product-1.jpg',
        alt:'product',
        size:['S','M','L', 'XL'],
        price:200.00,
        sale:true,
        salePrice:100.00,
        color:['green','red','white','black', 'yellow'],
        number: 3,    
    },
    {
        id:2,
        title:'Essential cotton',
        img:'./image/product/product-2.jpg',
        alt:'product',
        size:[],
        price:175.00,
        sale:false,
        salePrice:0,
        color:['green','white','black', 'blue'],
        number: 2,  
 
    },
    {
        id:3,
        title:'Striped cotton t-shirt',
        img:'./image/product/product-3.jpg',
        alt:'product',
        size:['S'],
        price:200.00,
        sale:false,
        salePrice:0,
        color:['black', 'lightgreen'],
        number: 5, 

    },
    {
        id:4,
        title:'Striped cotton t-shirt',
        img:'./image/product/product-4.jpg',
        alt:'product',
        size:[],
        price:100.00,
        sale:false,
        salePrice:0,
        color:['lightgreen', 'white'],
        number: 0, 
    },
    {
        id:5,
        title:'Message cotton t-shirt',
        img:'./image/product/product-6.jpg',
        alt:'product',
        size:['S','M','L', 'XL'],
        price:100.00,
        sale:false,
        salePrice:100.00,
        color:['green','red','white','black'],
        number: 3,    
    },
   {
        id:6,
        title:' t-shirt',
        img:'./image/product/product-7.jpg',
        alt:'product',
        size:[ 'XL'],
        price:200.00,
        sale:true,
        salePrice:100.00,
        color:['white','black', 'orange'],
        number: 5,    
    },
    {
        id:7,
        title:'Ruffle sleeve t-shirt',
        img:'./image/product/product-8.jpg',
        alt:'product',
        size:['S','M','L', 'XL'],
        price:100.00,
        sale:false,
        salePrice:0,
        color:['green','red','white','black'],
        number: 3,    
    },
   {
        id:8,
        title:'Double layer top',
        img:'./image/product/product-9.jpg',
        alt:'product',
        size:[ 'S','XL'],
        price:200.00,
        sale:false,
        salePrice:0,
        color:['white','black', 'yellow'],
        number: 5,    
    },
    {
        id:9,
        title:'Essential cotton-blend',
        img:'./image/product/product-1.jpg',
        alt:'product',
        size:['S','M','L', 'XL'],
        price:200.00,
        sale:true,
        salePrice:100.00,
        color:['green','red','white','black'],
        number: 3,    
    },
    {
        id:10,
        title:'Essential cotton',
        img:'./image/product/product-2.jpg',
        alt:'product',
        size:['S','M', 'XL'],
        price:175.00,
        sale:false,
        salePrice:0,
        color:['green','white','black'],
        number: 2,  
 
    },
    {
        id:11,
        title:'Striped cotton t-shirt',
        img:'./image/product/product-3.jpg',
        alt:'product',
        size:['S'],
        price:200.00,
        sale:false,
        salePrice:0,
        color:['black'],
        number: 5, 

    },
    {
        id:12,
        title:'Striped cotton t-shirt',
        img:'./image/product/product-4.jpg',
        alt:'product',
        size:[],
        price:100.00,
        sale:false,
        salePrice:0,
        color:['white'],
        number: 0, 
    },
    {
        id:13,
        title:'Message cotton t-shirt',
        img:'./image/product/product-6.jpg',
        alt:'product',
        size:['S','M','L', 'XL'],
        price:100.00,
        sale:false,
        salePrice:100.00,
        color:['green','red','while','black'],
        number: 3,    
    },
   {
        id:14,
        title:' t-shirt',
        img:'./image/product/product-7.jpg',
        alt:'product',
        size:[ 'XL'],
        price:200.00,
        sale:true,
        salePrice:100.00,
        color:['white','black'],
        number: 5,    
    },
    {
        id:15,
        title:'Ruffle sleeve t-shirt',
        img:'./image/product/product-8.jpg',
        alt:'product',
        size:['S','M','L', 'XL'],
        price:100.00,
        sale:false,
        salePrice:0,
        color:['green','red','white','black'],
        number: 3,    
    },
   {
        id:16,
        title:'Double layer top',
        img:'./image/product/product-9.jpg',
        alt:'product',
        size:[ 'S','XL'],
        price:200.00,
        sale:false,
        salePrice:0,
        color:['while','black'],
        number: 5,    
    },
    {
        id:17,
        title:'Ruffle sleeve t-shirt',
        img:'./image/product/product-8.jpg',
        alt:'product',
        size:['S','M','L', 'XL'],
        price:100.00,
        sale:false,
        salePrice:0,
        color:['green','red','while','black'],
        number: 3,    
    },
   {
        id:18,
        title:'Double layer top',
        img:'./image/product/product-9.jpg',
        alt:'product',
        size:[ 'S','XL'],
        price:200.00,
        sale:false,
        salePrice:0,
        color:['white','black'],
        number: 5,    
    },
    {
        id:19,
        title:'Ruffle sleeve t-shirt',
        img:'./image/product/product-8.jpg',
        alt:'product',
        size:['S','M','L', 'XL'],
        price:100.00,
        sale:false,
        salePrice:0,
        color:['green','red','white','black'],
        number: 3,    
    },
   {
        id:20,
        title:'Double layer top',
        img:'./image/product/product-9.jpg',
        alt:'product',
        size:[ 'S','XL'],
        price:200.00,
        sale:false,
        salePrice:0,
        color:['white','black'],
        number: 5,    
    },
]
